// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvgupcxbuvokdtrjmfwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2Z3VwY3hidXZva2R0cmptZndvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MTM1MjcsImV4cCI6MjA1NzQ4OTUyN30.couS-136KC7A58VeCaXMTMgb97R8ZkoFpF2bbilizQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);